-- Visual preview sessions
CREATE TABLE visual_preview_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_workspace_id UUID NOT NULL REFERENCES intake_workspaces(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'CLOSED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_visual_sessions_workspace ON visual_preview_sessions(intake_workspace_id);

-- Visual element selections
CREATE TABLE visual_selections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES visual_preview_sessions(id) ON DELETE CASCADE,
  selector TEXT NOT NULL,
  dom_path TEXT,
  text_content TEXT,
  bounding_box JSONB NOT NULL DEFAULT '{}',
  aria_role VARCHAR(100),
  screenshot_ref TEXT,
  page_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_visual_selections_session ON visual_selections(session_id);

-- Visual requirements (generated by Claude from selections + instructions)
CREATE TABLE visual_requirements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_workspace_id UUID NOT NULL REFERENCES intake_workspaces(id) ON DELETE CASCADE,
  selection_id UUID REFERENCES visual_selections(id) ON DELETE SET NULL,
  title VARCHAR(500) NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  user_goal TEXT NOT NULL DEFAULT '',
  target_area TEXT NOT NULL DEFAULT '',
  requested_change TEXT NOT NULL DEFAULT '',
  acceptance_criteria JSONB NOT NULL DEFAULT '[]',
  implementation_hints JSONB NOT NULL DEFAULT '[]',
  open_questions JSONB NOT NULL DEFAULT '[]',
  confidence NUMERIC(3, 2) NOT NULL DEFAULT 0.80,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'ACCEPTED', 'ARCHIVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_visual_reqs_workspace ON visual_requirements(intake_workspace_id);
